<?php

/**
* Clase Principal de la Aplicación.
*
* LICENSE:  This file is part of mvCaptcha.
* mvCaptcha is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* mvCaptcha is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with SGU.  If not, see <http://www.gnu.org/licenses/>.
*
* @copyright  Copyright (c) 2010 WALTER CERRUDO (http://walterio.netau.net)
* @license    http://www.gnu.org/licenses/   GPL License
* @version    0.9
* @link       http://walterio.netau.net
* @since      File available since Release 1.0
*/

require('./class/captcha-2.0.1/captcha.class.php');
require './class/imagemask/class.imagemask.php';

class mvcaptcha
{
	var $URLOK;
	var $URLFallo;
	var $CaptchaSERVER;
	var $CaptchaUSER;
	
    /**
    * @return mvcaptcha
    * @desc Class constructor.
    */
	function mvcaptcha() {
		;
	}
	
	/**
    * @return void
    * @param string $parURLOK URL destination if the captcha is successful	
	* @param string $parURLFALLA URL destination if the captcha is successful
    * @desc Create CAPTCHA
    */
	function crearmvcaptcha($parURLOK,$parURLFALLA) {
		$this->URLOK=$parURLOK;
		$this->URLFallo=$parURLFALLA;
		$captcha = new captcha();
		$_SESSION['CAPTCHAString']=$captcha->CaptchaString;
		$_SESSION['URLOK']=$this->URLOK;
		$_SESSION['URLFALLO']=$this->URLFallo;
		$this->generarMask();
		
		;
	}
	
	/**
    * @return boolean
    * @desc Comprueba si se ingresaron datos
    */	
	function verformulario() {
		return !isset($_POST['aceptar']);
		;
	}	
	
	/**
    * @return void
    * @param integer $mask Color sobre el cual aplicar la mascara
    * @
    * @desc Apply the mask
    */	
	function generarMask() {
	$rndImg=mt_rand(1, 4);
	$im = new imageMask('FFFFFF');
    $im->setDebugging(true);
    $im->maskOption('centre');
    if ($im->loadImage("./tmp/captcha.png"))
    {
        if ($im->applyMask("./img/mask/mask".$rndImg."a.png"))
        {
            //$im->showImage('png');
            if (!$im->saveImage('./tmp/img1.png',100)) echo 'error img1';
        }        
    }
        
    $im = imagecreatefrompng('./tmp/img1.png');
	$bg_color = hexdec('ffffff');
	imagecolortransparent($im, $bg_color);
	imagepng($im,'./tmp/img1.png',9);    
   	
    $im = new imageMask('FFFFFF');
    $im->setDebugging(true);
    $im->maskOption('centre');
    if ($im->loadImage("./tmp/captcha.png"))
    {
        if ($im->applyMask("./img/mask/mask".$rndImg."b.png"))
        {
            //$im->showImage('png');
            if (!$im->saveImage('./tmp/img2.png',100)) echo 'error img1';
        }  
    }
    $im = imagecreatefrompng('./tmp/img2.png');
	$bg_color = hexdec('ffffff');
	imagecolortransparent($im, $bg_color);
	imagepng($im,'./tmp/img2.png',9);

	unlink('./tmp/captcha.png'); 
		;
	}
	/**
    * @return void
    * @desc Redirect
    */		
	function proceder() {
		if ($this->getCaptchaSERVER()==$this->getCaptchaUSER())
		{
			header ("Location: ".$_SESSION['URLOK']);
		}
		else 
		{
			header ("Location: ".$_SESSION['URLFALLO']);
		}
		;
	}
	
	/**
    * @return string
    * @desc Get user input string
    */	
	function getCaptchaUSER() {
		$this->CaptchaUSER=$_POST['captchastring'];
		return $this->CaptchaUSER;
		;
	}

	/**
    * @return string
    * @desc Get string generated by the server
    */	
	function getCaptchaSERVER() {
		$this->CaptchaSERVER=$_SESSION['CAPTCHAString'];
		return $this->CaptchaSERVER;
		;
	}	
	
	/**
    * @return string
    * @desc Generar salida HTML
    */	
	function getHTML() {
		$html="
			<link href=\"css/styles.css\" rel=\"stylesheet\" type=\"text/css\" >
			<style type=\"text/css\" media=\"screen, projection\">
			#parallax {
				position: relative;
				overflow: hidden;
				width: 100%;
				height: 75px;
			}
			
			#content {
				text-align: center;
			 	}
			.freeze     {  }
			.clasecss{
			   background-color: #ff8800;
			   font-weight: bold;
			}
			 	
			</style>
			
			<script
				type=\"text/javascript\" src=\"./js/jquery-1.3.2.min.js\"></script>
			<script
				type=\"text/javascript\" src=\"./js/jquery.jparallax.091.js\"></script>
			<script type=\"text/javascript\">
			<!--
			var inPullNav = false;  
			jQuery(document).ready(function(){
					var corners='';  
				 	jQuery('#parallax').jparallax({
					 	mouseport: jQuery('#parallax')},{yparallax: false},{xtravel:-0.8, ytravel:-0.5}, {xtravel:0.8, ytravel:-0.8}).append(corners);
			});
			//-->
			</script>
			<!--[if lt IE 7]>
			<script type=\"text/javascript\" src=\"js/jquery.ifixpng.js\"></script>
			<script type=\"text/javascript\">jQuery(document).ready(function(){ jQuery('img[@src$=.png]').ifixpng(); });</script>
			<![endif]-->
			<!--[if lt IE 8]>
			<style type=\"text/css\">
			@import \"css/style_ie.css\";
			</style>
			</head>
			</body>
			<![endif]-->
			<table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">
				<tr>
					<td align=\"center\" class=\"descdet\">
					<div class=\"bordeder\">
						<div id=\"content\"><strong class=\"subder\">MVCaptcha</strong><br>
									Ingresar el texto mostrado en la imagen <br>
									Mueve el Mouse para formar el texto
									<br />
									<a href=\"./\"><img src=\"./img/recargar.png\" alt=\"colabora\" width=\"32\" height=\"32\" border=\"0\"></a>
									<div id=\"formulariomayores\" style=\"display: none; \"></div>
									<div id=\"parallax\" class=\"clear\" style=\"background: url(./img/back/back".mt_rand(1, 4).".png) center;\">
										<div style=\"width: 216px; height: 75px\">
											<img src=\"tmp/img1.png\" alt=\"\" style=\"position:absolute;left:".mt_rand(30, 40)."px?>px;top:0px;\">
										</div>
										<div style=\"width: 216px; height: 75px;\">
											<img src=\"tmp/img2.png\" alt=\"\" style=\"position:absolute;left:".mt_rand(30, 40)."px;top:0px;\">
										</div>
									</div>
					
								</div>
								
						<form action=\"./\" method=\"POST\">
					<p><input type=\"text\" name=\"captchastring\" size=\"30\" style=\"font-size: 18px;\"> <br> &#40;sEnSiblE a MayUsCulAs!&#41;</p>
					
					<p><input type=\"submit\" name=\"aceptar\" value=\"Comparar\" ></p></form>
					<p>
					<a href=\"http://jigsaw.w3.org/css-validator/check/referer\">
				    	<img style=\"border:0;\" src=\"./img/cssval.gif\"  alt=\"¡CSS Válido!\" >
					</a>
				
				    <a href=\"http://validator.w3.org/check?uri=referer\">
				    	<img src=\"./img/htmlval.gif\" style=\"border:0;\" alt=\"HTML 4.01 Strict Válido\" >
				    </a>
				  	</p>					
					</div>
					</td>
				</tr>
			</table>";
		return $html;
		;
	}
}
?>
